# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  schedule: [{cron: "0 */6 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["usb-otg"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Hades785
          template: classic
          base: header, activity, community, repositories, metadata
          config_twemoji: yes
          config_display: large
          config_octicon: yes
          config_timezone: Europe/Paris
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories,user
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: percentage,bytes-size
          plugin_languages_limit: 8
          plugin_languages_other: yes
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_skipped: upssitech-filrouge,nsggp-game
          plugin_languages_threshold: 10%
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base,repositories
          plugin_lines_skipped: upssitech-filrouge,nsggp-game
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_repositories: yes
          plugin_notable_skipped: upssitech-filrouge,nsggp-game
          plugin_notable_types: commit,pull_requet
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_thanks: ludichat,watduhhekbro,dmitmel
          plugin_people_types: thanks
          repositories_skipped: upssitech-filrouge,nsggp-game
          
          # Output
          committer_gist: d3b5ce8669d61fed1ba0f61b06c62f22
          output_action: gist
